---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-telegram-client-k8s-deployment
spec:
  selector:
    matchLabels:
      app: dev-telegram-client-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: dev-telegram-client-k8s
    spec:
      containers:
        - name: dev-telegram-client-k8s
          image: registry.digitalocean.com/resty-registry/dev-telegram-client:latest
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: dev-telegram-client-service
spec:
  selector:
    app: dev-telegram-client-k8s
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3001
