export enum OrdersEvents {
	CANCELED = "CANCELED",
	PTO_REJECTED = "PTO_REJECTED",
	PTO_APPROVED = "PTO_APPROVED",
	APPROVED = "APPROVED",
	REJECTED = "APPROVED",
	TABLE_APPROVED = "TABLE_APPROVED",
	TABLE_REJECTED = "TABLE_REJECTED",
}
