export enum OrdersEvents {
	CREATE_ORDER = "CREATE_ORDER",
	REQUEST_TO_CONFIRM_ORDER = "REQUEST_TO_CONFIRM_ORDER",
	REQUEST_TO_CONFIRM_PAYMENT = "REQUEST_TO_CONFIRM_PAYMENT",
	CONFIRM_ORDER = "CONFIRM_ORDER",
	CONFIRM_PAYMENT = "CONFIRM_PAYMENT"
}
