export enum OrdersEvents {
	CANCELED = "ORDER_CANCELED",
	PTO_REJECTED = "ORDER_PTO_REJECTED",
	PTO_APPROVED = "ORDER_PTO_APPROVED",
	APPROVED = "ORDER_APPROVED",
	REJECTED = "ORDER_APPROVED",
	TABLE_APPROVED = "ORDER_TABLE_APPROVED",
	TABLE_REJECTED = "ORDER_TABLE_REJECTED",
}
